name: Setup
description: Setup Env

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Setup Java Env
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android SDK licenses
      shell: bash
      run: |
        set +o pipefail
        yes 2>/dev/null | sdkmanager --licenses

    - name: Install Android SDK components
      shell: bash
      run: sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;26.1.10909125"

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "cachedir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ${{ steps.npm-cache-dir.outputs.cachedir }}
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-

    - name: Install dependencies
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        npm ci
